config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'users#new'
  resources :tasks
  resources :sessions
  resources :users, only:[:new, :create, :show]
  namespace :admin do
    resources :users, only:[:index, :edit, :update, :new, :create, :show, :destroy]
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :duedate, presence: true
  validates :status, presence: true
  validates :priority, presence: true
  enum priority: { low: 0, medium: 1, high: 2 }
  paginates_per 6
  belongs_to :user, optional: true
  has_many :task_labels, dependent: :destroy
  has_many :labels, through: :task_labels
end

app/controllers/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user
  before_action :logged_in?
  before_action :set_labels, only: [:new, :create, :edit, :update]
  PER = 6

  def index
    @search_params = task_search_params
    if params[:title].present? && params[:status].present? && params[:labels].present?
     @tasks = Task.where('title LIKE ? AND status LIKE ?', "%#{params[:title]}%", "%#{params[:status]}%").joins(:labels).where(labels: params[:labels])
    elsif params[:title].present? && params[:status].present?
      @tasks = Task.where('title LIKE ? AND status LIKE ?', "%#{params[:title]}%", "%#{params[:status]}%")
    elsif params[:title].present? && params[:labels].present?
      @tasks = Task.where('title LIKE ?', "%#{params[:title]}%").joins(:labels).where(labels: params[:labels])
    elsif params[:status].present? && params[:labels].present?
      @tasks = Task.where(status: params[:status]).joins(:labels).where(labels: params[:labels])
    elsif params[:title].present?
      @tasks = Task.where('title LIKE ?', "%#{params[:title]}%")
    elsif params[:status].present?
      @tasks = Task.where(status: params[:status])
    elsif params[:labels].present?
      @tasks = Task.joins(:labels).where(labels: params[:labels])
    elsif params[:sort_creation]
      @tasks = current_user.tasks.order(created_at: :desc).page(params[:page]).per(PER)
    elsif params[:sort_priority]
      @tasks = current_user.tasks.order(priority: :desc).page(params[:page]).per(PER)
    else
      @tasks = Task.where(user_id: @current_user.id).order(duedate: :desc).page(params[:page]).per(PER)
    end
  end

  def new
    if params[:back]
      @task = Task.new(task_params)
      @task.duedate = Date.today
    else
      @task = Task.new
    end
  end

  def show
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    if params[:back]
      render :new
    else
      if @task.save
        flash[:success] = 'Task created'
        redirect_to tasks_path
      else
        flash.now[:danger] = 'Task cannot be created'
        render :new
      end
    end
  end

  def update
    if @task.update(task_params)
      flash[:success] = 'Task updated'
      redirect_to tasks_path
    else
      flash.now[:danger] = 'Task not updated'
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success] = 'Task deleted'
    redirect_to tasks_path
  end

  private
  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def set_labels
    @labels = Label.all
  end

  def task_search_params
    params.fetch(:search, {}).permit(:title, :status, :label_id )
  end

  def task_params
    params.require(:task).permit(:title, :content, :duedate, :priority, :status, :id, { label_ids: [] })
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user
  before_action :logged_in?
  before_action :set_labels, only: [:new, :create, :edit, :update]
  PER = 6

  def index
    @search_params = task_search_params
    if params[:title].present? && params[:status].present? && params[:labels].present?
     @tasks = Task.where('title LIKE ? AND status LIKE ?', "%#{params[:title]}%", "%#{params[:status]}%").joins(:labels).where(labels: params[:labels])
    elsif params[:title].present? && params[:status].present?
      @tasks = Task.where('title LIKE ? AND status LIKE ?', "%#{params[:title]}%", "%#{params[:status]}%")
    elsif params[:title].present? && params[:labels].present?
      @tasks = Task.where('title LIKE ?', "%#{params[:title]}%").joins(:labels).where(labels: params[:labels])
    elsif params[:status].present? && params[:labels].present?
      @tasks = Task.where(status: params[:status]).joins(:labels).where(labels: params[:labels])
    elsif params[:title].present?
      @tasks = Task.where('title LIKE ?', "%#{params[:title]}%")
    elsif params[:status].present?
      @tasks = Task.where(status: params[:status])
    elsif params[:labels].present?
      @tasks = Task.joins(:labels).where(labels: params[:labels])
    elsif params[:sort_creation]
      @tasks = current_user.tasks.order(created_at: :desc)
    elsif params[:sort_priority]
      @tasks = current_user.tasks.order(priority: :desc)
    else
      @tasks = Task.where(user_id: @current_user.id).order(duedate: :desc).page(params[:page]).per(PER)
    end
  end

  def new
    if params[:back]
      @task = Task.new(task_params)
      @task.duedate = Date.today
    else
      @task = Task.new
    end
  end

  def show
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    if params[:back]
      render :new
    else
      if @task.save
        flash[:success] = 'Task created'
        redirect_to tasks_path
      else
        flash.now[:danger] = 'Task cannot be created'
        render :new
      end
    end
  end

  def update
    if @task.update(task_params)
      flash[:success] = 'Task updated'
      redirect_to tasks_path
    else
      flash.now[:danger] = 'Task not updated'
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success] = 'Task deleted'
    redirect_to tasks_path
  end

  private
  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def set_labels
    @labels = Label.all
  end

  def task_search_params
    params.fetch(:search, {}).permit(:title, :status, :label_id )
  end

  def task_params
    params.require(:task).permit(:title, :content, :duedate, :priority, :status, :id, { label_ids: [] })
  end
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
<% if @task.errors.any? %>
  <div class="bg-danger text-white">
    <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li>・<%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div class="field">
    <p class="text-left">
    <%= form.text_field :title, placeholder: 'Task Name' %>
    <%= form.text_field :content, placeholder: 'Task Details' %>
    <%= form.date_field :duedate, placeholder: 'Deadline' %>
    <%= form.select :status, ['pending','started','completed'], placeholder: 'Status' %>
    <%= form.select :priority,['low','medium','high'], placeholder: 'Priority' %>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
    <%= form.submit "Submit", class:"btn btn-primary" %>
    </p>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="card p-5" style= "width: 110rem" id="textfield">
  <h1>Editing Task</h1>
  <div class="mb-5">
    <%= form_with(model: @task, local: true) do |form| %>
    <% if @task.errors.any? %>
      <div class="bg-danger text-white">
        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li>・<%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <div class="field">
        <ul>
          <li><%=form.label :title %></li>
          <li><%= form.text_field :title, placeholder: 'Task Name' %></li>
          <li><%=form.label :content %></li>
          <li><%= form.text_field :content, placeholder: 'Task Details' %></li>
          <li><%=form.label :duedate %></li>
          <li><%= form.date_field :duedate, placeholder: 'Deadline' %></li>
          <li><%=form.label :status %></li>
          <li><%= form.select :status, ['pending','started','completed'], placeholder: 'Status' %></li>
          <li><%=form.label :priority %></li>
          <li><%= form.select :priority,['low','medium','high'], placeholder: 'Priority' %></li>
          <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
          <%= form.submit "Submit", class:"btn btn-primary" %>
        </ul>


      </div>
    <% end %>
  </div>
  <span><%= link_to 'Show', @task, class:"btn btn-info" %>
  <%= link_to 'Back', tasks_path, class:"btn btn-warning" %></span>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="card">
  <%= link_to root_path do %><h1>Tasks</h1><% end %>
  <p id="notice"><%= notice %></p>
  <div class="container-fluid">
    <%= form_with(url: tasks_path, method: :get, local: true, class: "form-inline") do |f| %>
      <div class="field">
        <%= f.search_field :title, placeholder: 'title keyword', value: @search_params[:title] %>
        <%= f.select :status, ["pending", "started", "completed" ], placeholder: 'status', selected: @search_params[:status], include_blank: "" %>
        <% Label.all.each do |label| %>
          <%= label.name %>:<%= f.check_box :labels, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
        <% end %>
        <%= f.submit "search", class: "btn btn-primary"  %>
      </div>
    <% end %>

    <p class="mt-4">
      <span><%= link_to 'New Task', new_task_path, class: "btn btn-warning btn-lg" %></span>
      <span><%= link_to 'New Label', new_label_path, class: "btn btn-success btn-lg" %></span>
    </p>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">No.</th>
          <th scope="col">Name</th>
          <th scope="col">Details</th>
          <th scope="col"><%= link_to 'Sort by creation', tasks_path(sort_creation: "true") %></th>
          <th scope="col"><%= link_to 'Sort by duedate', tasks_path(sort_duedate: "true") %></th>
          <th scope="col">Status</th>
          <th scope="col"><%= link_to 'Sort by priority', tasks_path(sort_priority: "true") %></th>
          <th scope="col">Labels</th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <% t=0 %>

      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td><%= t += 1 %></td>
            <td><%= link_to task.title ,task_path(task.id) %></td>
            <td><%= task.content %></td>
            <td><%= task.created_at.strftime('%Y/%-m/%-d') %></td>
            <td><%= task.duedate.strftime('%Y/%-m/%-d') %></td>
            <td><%= task.status %></td>
            <td><%= task.priority %></td>
            <td>
              <% task.labels.each do |label| %>
                [<%= label.name %>]
              <% end %>
            </td>
            <td><%= link_to 'Show', task, class: "btn btn-warning" %></td>
            <td><%= link_to 'Edit', edit_task_path(task), class: "btn btn-info" %></td>
            <td><%= button_to 'Delete', task_path(task.id), :method=>:delete, :class=>:destroy, class:"btn btn-danger btn-lg" %></td>
          </tr>
        <% end %>
        <br>
      </tbody>
    </table>
    <hr>
    <%= paginate @tasks, class:"mt-5" %>
  </div>
</div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path, class: "btn btn-info btn-lg" %>

app/views/tasks/show.html.erb
<div >
  <div class="card" style="width: 110rem">
    <div class="pclass">


    <p>
      <strong>Title:</strong>
      <%= @task.title %>
    </p>

    <p>
      <strong>Content:</strong>
      <%= @task.content %>
    </p>

    <p>
      <strong>Duedate:</strong>
      <%= @task.duedate %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @task.status %>
    </p>

    <p>
      <strong>Priority:</strong>
      <%= @task.priority %>
    </p>

    <p>
      <strong>Labels:</strong>
      <% @task.labels.each do |label| %>
        [<%= label.name %>]
      <% end %>
    </p>
    <p>
    <%= link_to 'Edit', edit_task_path(@task) %>  |
    <%= link_to 'Back', tasks_path %>
    </p>
  </div>
</div>
</div>