config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'users#new'
  resources :tasks
  resources :sessions
  resources :users, only:[:new, :create, :show]
  namespace :admin do
    resources :users, only:[:index, :edit, :update, :new, :create, :show, :destroy]
  end
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :task_labels, dependent: :destroy
  has_many :tasks, through: :task_labels
end

app/controllers/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]

  def index
    @labels = Label.all
  end

  def show
  end

  def new
    @label = Label.new
  end

  def edit
  end

  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: 'Label was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to @label, notice: 'Label was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'Label was successfully destroyed.' }
    end
  end

  private
  def set_label
    @label = Label.find(params[:id])
  end

  def label_params
    params.require(:label).permit(:name)
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: 'name' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<div class="card p-5" style= "width: 110rem" id="textfield">
  <h1>Editing Label</h1>
  <div class="mb-5">
<%= render 'form', label: @label %>

<%= link_to 'Show', @label, class:"btn btn-info" %> |
<%= link_to 'Back', labels_path, class:"btn btn-warning" %>
</div>
</div>

app/views/labels/index.html.erb
<div class="container">
  <div class="card p-5">
<p id="notice"><%= notice %></p>

<h1 class="mb-5">Labels</h1>

<span class="mb-4"><%= link_to 'New Label', new_label_path, class: "btn btn-primary" %></span>

<table class="text-md-left table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td><%= link_to 'Show', label, class: "btn btn-warning" %></td>
        <td><%= link_to 'Edit', edit_label_path(label), class: "btn btn-info" %></td>
        <td><%= button_to 'Delete', label_path(label.id), :method=>:delete, :class=>:destroy, class:"btn btn-danger btn-lg" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>
</div>
</div>

app/views/labels/new.html.erb
<h1>New Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="card" style="width: 110rem">
    <div class="pclass">
<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>

<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>
</div>
</div>