config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'users#new'
  resources :tasks
  resources :sessions
  resources :users, only:[:new, :create, :show]
  namespace :admin do
    resources :users, only:[:index, :edit, :update, :new, :create, :show, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  before_validation { email.downcase! }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
  has_many :tasks, dependent: :destroy
  before_destroy :before_admin_destroy
  before_update :before_admin_update

  private
  def before_admin_destroy
    throw(:abort) if User.where(admin: true).count <= 1 && self.admin == true
  end

  def before_admin_update
    if User.where(admin: true).count == 1 && self.admin == false
      errors.add(:admin,"Atleast one admin is required")
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_necessary
  PER = 6

  def index
    @users = User.select(:id, :name, :email, :admin).order(created_at: :asc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "new user added"
      redirect_to admin_users_path(@user.id)
    else
      flash.now[:danger] = "User registration failed"
      render :new
    end
  end

  def show
    @tasks = Task.where(user_id: @user.id).page(params[:page]).per(PER)
  end

  def edit
  end

  def update
    puts @user
    if @user.update(user_params)
      flash[:success] = "update successful"
      redirect_to admin_user_path(@user)
    else
      flash.now[:danger] = "update failed"
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "user deleted!"
      redirect_to admin_users_path
    else
      flash[:danger] = "user not deleted"
      redirect_to admin_users_path
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def admin_necessary
    unless current_user.admin?
      flash[:danger] = "only for admins！"
      redirect_to tasks_path
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
end

app/controllers/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_necessary
  PER = 10

  def index
    @users = User.select(:id, :name, :email, :admin).order(created_at: :asc).page(params[:page]).per(PER)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "new user added"
      redirect_to admin_users_path(@user.id)
    else
      flash.now[:danger] = "User registration failed"
      render :new
    end
  end

  def show
    @tasks = Task.where(user_id: @user.id).page(params[:page]).per(PER)
  end

  def edit
  end

  def update
    puts @user
    if @user.update(user_params)
      flash[:success] = "update successful"
      redirect_to admin_user_path(@user)
    else
      flash.now[:danger] = "update failed"
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "user deleted!"
      redirect_to admin_users_path
    else
      flash[:danger] = "user not deleted"
      redirect_to admin_users_path
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def admin_necessary
    unless current_user.admin?
      flash[:danger] = "only for admins！"
      redirect_to tasks_path
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
end

app/controllers/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, { only: [:index, :show, :edit, :update] }
  PER = 6

  def new
    @user = User.new
    if logged_in?
      redirect_to tasks_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'User was successfully created'
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = current_user
    @tasks = @user.tasks&.page(params[:page]).per(PER)
    redirect_to tasks_path if @user.id !=  params[:id].to_i
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = 'Task not deleted'
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, @user], local: true, url: choose_new_or_edit) do |f| %>
  <% if @user.errors.any? %>
    <div class="bg-danger text-white">
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li>・<%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>

  <div class="field">
    <%= f.text_field :name, placeholder: 'name', class:"form-control"  %>
    <%= f.email_field :email, placeholder: 'email', class:"form-control"  %>
    <%= f.password_field :password, placeholder: 'password', class:"form-control"  %>
    <%= f.password_field :password_confirmation, placeholder: 'password_confirmation', class:"form-control"  %>
    <%= f.label :admin %>
    <%= f.check_box :admin, {}, 'true', 'false' %>
    <%= f.submit "Submit", class:"btn btn-primary" %>
    <% end %>
  </div>

app/views/admin/users/edit.html.erb
<h1 class = "center">Edit</h1>

<%= render 'form', user: @user %>

<%= link_to "return", admin_users_path %>

app/views/admin/users/index.html.erb
<h1 class = "center">List of Users</h1>
<br>
<div class="adm">

<%= link_to 'Create user', new_admin_user_path, class: "btn btn-info" %>
<hr>

<table class ="table table-striped">
  <thead>
    <tr>
      <th>UserID</th>
      <th>Username</th>
      <th>Email</th>
      <th>No. of tasks</th>
      <th>User admin priviledges</th>
      <th colspan="4"></th>
   </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= link_to user.name, admin_user_path(user.id) %></td>
      <td><%= user.email %></td>
      <td><%= user.tasks.length %></td>
      <td><%= user.admin? ? "Yes":"No" %></td>
      <td><%= link_to 'Show', admin_user_path(user.id), class: "btn btn-warning" %></td>
      <td><%= link_to 'Edit', edit_admin_user_path(user.id), class: "btn btn-success" %></td>
      <td><%= button_to 'Delete', admin_user_path(user.id), :method=>:delete, :class=>:destroy, class:"btn btn-danger btn-lg" %>
    </tr>
    <% end %>
  </tbody>
</table>
<hr>
<%= paginate @users, class:"mt-5" %>
</div>

app/views/admin/users/new.html.erb
<h1 class = "center">Register</h1>

<%= render 'form', user: @user %>

<%= link_to 'return', admin_users_path %>

app/views/admin/users/show.html.erb
<h1 class = "center"><%= @user.name %>'s page</h1>
<div class="adm">
<div class ="col-md-6">
  <table class="user_show_table  clearfix">
    <thead>
      <tr>
        <th>ID</th>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <th>Username</th>
        <td><%= @user.name%></td>
      </tr>
      <tr>
        <th>Email</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>No. of tasks</th>
        <td><%= @user.tasks.count %></td>
      </tr>
      <tr>
        <th>User admin priviledges</th>
        <td><%= @user.admin? ? "Yes":"No" %></td>
      </tr>
        <td>Return to User Management <%= link_to 'Back', admin_users_path, class: 'btn btn-primary btn-lg' %>
      </td>
    </thead>
  </table>
</div>
<br>
<hr>
<br>
<div class ="text-right">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Duedate</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Label</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.duedate.strftime('%Y/%-m/%-d') %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td>
          <% task.labels.each do |label| %>
            <%= label.name %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>